T_max: 64
a2a_radius: 50.0
a2m_radius: 150.0
accelerator: auto
dataset: argoverse_v2
devices: 1
dropout: 0.1
head_dim: 16
hidden_dim: 128
input_dim: 2
lr: 0.0005
max_epochs: 64
num_agent_layers: 2
num_dec_layers: 2
num_freq_bands: 64
num_future_steps: 60
num_heads: 8
num_historical_steps: 50
num_map_layers: 1
num_modes: 6
num_recurrent_steps: 3
num_t2m_steps: 30
num_workers: 8
output_dim: 2
output_head: false
persistent_workers: true
pin_memory: true
pl2a_radius: 50.0
pl2m_radius: 150.0
pl2pl_radius: 150.0
root: D:\\argoverse2
shuffle: true
submission_dir: ./
submission_file_name: submission
test_batch_size: 4
test_processed_dir: D:\\argoverse2\\test\\processed
test_raw_dir: null
time_span: 10
train_batch_size: 4
train_processed_dir: D:\\argoverse2\\train\\processed
train_raw_dir: null
val_batch_size: 4
val_processed_dir: D:\\argoverse2\\val\\processed
val_raw_dir: null
weight_decay: 0.0001
