T_max: 64
a2a_radius: 50
a2m_radius: 150
dataset: argoverse_v2
dropout: 0.1
head_dim: 16
hidden_dim: 128
input_dim: 2
lr: 0.0005
num_agent_layers: 2
num_dec_layers: 2
num_freq_bands: 64
num_future_steps: 60
num_heads: 8
num_historical_steps: 50
num_map_layers: 1
num_modes: 6
num_recurrent_steps: 1
num_t2m_steps: null
output_dim: 2
output_head: 2
pl2a_radius: 50
pl2m_radius: 50
pl2pl_radius: 50
submission_dir: ./
submission_file_name: submission
time_span: null
weight_decay: 0.0001
